services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: naves-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:starshipdb
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.h2.Driver
      - SPRING_DATASOURCE_USERNAME=w2m-user
      - SPRING_DATASOURCE_PASSWORD=w2m-password
      - SPRING_H2_CONSOLE_ENABLED=true