spring:
  application:
    name: Naves
  datasource:
    url: jdbc:h2:mem:starshipdb
    driverClassName: org.h2.Driver
    username: w2m-user
    password: w2m-password
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    enabled: true
springdoc:
  api-docs:
    title: API de Naves Espaciales
    description: API RESTful para el mantenimiento CRUD de naves espaciales de series y películas
    version: OPENAPI_3_0
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
logging:
  level:
    root: INFO
    com.w2m.spaceships.aspect: WARN
main:
  allow-circular-references: true
rabbitmq:
  host: localhost
  port: 5672
  username: guest
  password: guest
  queue: spaceShipQueue
  exchange: spaceShipExchange
  routingkey: spaceShipRoutingKey