spring:
  application:
    name: Naves
  datasource:
    url: jdbc:h2:mem:starshipdb
    driverClassName: org.h2.Driver
    username: w2m-user
    password: w2m-password
  h2:
    console:
      enabled: true
      path: /h2-console
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    enabled: true
springdoc:
  api-docs:
    title: API de Naves Espaciales
    description: API RESTful para el mantenimiento CRUD de naves espaciales de series y películas
    version: OPENAPI_3_0
  swagger-ui:
    enabled: true
    path: /swagger-ui.html